export const courses = [
  { slug: 'digital-marketing', name: 'Digital Marketing', category: 'Marketing', tag: 'Create Your Impact', icon: 'Megaphone', color: '#e9eeff', image: 'photo-1460925895917-afdab827c52f', description: 'Turn your creativity into campaigns that connect. Explore the world of brands, content and digital growth.', topics: ['Search & discovery', 'Social media strategy', 'Content & storytelling', 'Campaign measurement'], tools: ['Digital platforms', 'Content tools', 'Analytics'], careers: ['Digital marketing executive', 'Social media executive', 'Content marketer'] },
  { slug: 'multimedia', name: 'Multimedia', category: 'Design', tag: 'Make Ideas Visible', icon: 'Palette', color: '#fff0e4', image: 'photo-1626785774573-4b799315345d', description: 'Bring ideas to life through visual design. Find your creative voice across graphics and digital media.', topics: ['Design foundations', 'Visual communication', 'Digital graphics', 'Creative portfolio'], tools: ['Design software', 'Digital media tools'], careers: ['Graphic designer', 'Visual designer', 'Multimedia artist'] },
  { slug: 'interior-designing', name: 'Interior Designing', category: 'Design', tag: 'Reimagine Every Space', icon: 'Armchair', color: '#e8efea', image: 'photo-1600210492486-724fe5c67fb0', description: 'Explore the meeting point of creativity and function. Take your first step into the world of interior spaces.', topics: ['Design principles', 'Space planning', 'Materials & finishes', 'Design presentation'], tools: ['Drafting tools', 'Visualisation software'], careers: ['Junior interior designer', 'Design assistant', 'Space planning assistant'] },
  { slug: 'accounting', name: 'Accounting', category: 'Business', tag: 'Build Business Confidence', icon: 'Calculator', color: '#f2ecff', image: 'photo-1450101499163-c8848c66ca85', description: 'Understand the numbers behind every business. Discover accounting and the tools used in a modern workplace.', topics: ['Accounting foundations', 'Business transactions', 'Computerised accounting', 'Financial reporting'], tools: ['Tally Prime', 'Spreadsheets'], careers: ['Accounts assistant', 'Junior accountant', 'Bookkeeping assistant'] },
  { slug: 'ms-office', name: 'MS Office', category: 'Business', tag: 'Work Smarter Every Day', icon: 'Table2', color: '#e7f2f8', image: 'photo-1499951360447-b19be8fe80f5', description: 'Build everyday digital confidence with the productivity skills that support study, work and business.', topics: ['Document creation', 'Spreadsheet foundations', 'Presentation design', 'Office productivity'], tools: ['Word', 'Excel', 'PowerPoint'], careers: ['Office assistant', 'Administrative assistant', 'Data entry operator'] },
  { slug: 'sap', name: 'SAP', category: 'Business', tag: 'Understand The Enterprise', icon: 'Layers3', color: '#e6f0ff', image: 'photo-1460925895917-afdab827c52f', description: 'Discover how connected business processes work. Explore the enterprise software behind modern organisations.', topics: ['ERP foundations', 'Business workflows', 'Module-based learning', 'Practical scenarios'], tools: ['SAP — module to be confirmed'], careers: ['ERP support trainee', 'SAP end-user roles', 'Business operations assistant'] },
  { slug: 'skill-developments', name: 'Skill Developments', category: 'Technology', tag: 'Build What Comes Next', icon: 'Code2', color: '#eaeafa', image: 'photo-1498050108023-c5249f4df085', description: 'Go from curious to creator. Explore programming and data skills, and start solving problems with technology.', topics: ['Programming foundations', 'Problem solving', 'Working with data', 'Project development'], tools: ['Python', 'Data analytics tools'], careers: ['Junior developer', 'Programming trainee', 'Data analytics trainee'] },
];
export const site = { name: 'G-TEC Mahe', url: 'https://gtecmahe.com', address: 'Near Full Cart Supermarket, Parimadam, New Mahe, Thalassery, Kerala 673311', mapUrl: 'https://maps.app.goo.gl/NcbyvmiELrYXGfTdA', phone: '9745099220', phoneSecondary: '9745399220', email: 'mahe.knr@gteceducation.com', instagram: 'https://www.instagram.com/gtec_mahe?stkn=c3pucDJmYTd4cGxo', facebook: 'https://www.facebook.com/gtecmahe', linkedin: 'https://www.linkedin.com/company/gtec-mahe/', whatsapp: 'https://wa.me/message/YN52QJSMD3MGB1', whatsappNumber: (import.meta.env.VITE_WHATSAPP_NUMBER || '').replace(/\D/g, ''), enquiryEndpoint: import.meta.env.VITE_ENQUIRY_ENDPOINT || '' };
export const faqs = [
  ['How do I choose the right course?', 'Start with what interests you: technology, design, marketing or business. Our enquiry form lets you tell an advisor about your goals so you can discuss a suitable course.'],
  ['Can I join as a beginner?', 'Entry requirements depend on the course and level you choose. Share your education and experience with admissions to confirm the right starting point.'],
  ['What are the course duration and fees?', 'Duration, fees and batch schedules vary by programme. Request the current course details from admissions before enrolling.'],
  ['Is placement support available?', 'G-TEC Mahe describes placement assistance as part of its learner support. Ask the team about the current process and eligibility. Placement assistance does not guarantee employment.'],
  ['Will I receive a certificate?', 'Ask admissions to confirm the exact qualification, awarding body, assessment requirements and any additional certification fees for your selected programme.'],
  ['Where is G-TEC Mahe located?', site.address + '. You can find directions in the contact section below.'],
];

